// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uipfticcberaaghwkyfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcGZ0aWNjYmVyYWFnaHdreWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTQwNTcsImV4cCI6MjA2Mzc3MDA1N30.-ep1_P_jWUG6lmbm7gH3V7pAsDFtkCWcctYM4fT6Azw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);